# Generated by Django 3.0.5 on 2020-05-07 12:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0003_auto_20200427_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='book',
            name='peopleInterested',
            field=models.ManyToManyField(blank=True, null=True, related_name='bookInterested', to=settings.AUTH_USER_MODEL),
        ),
    ]
