# Generated by Django 3.0.5 on 2020-05-22 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20200507_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='matchedWith',
            field=models.ManyToManyField(blank=True, null=True, related_name='_book_matchedWith_+', to='books.Book'),
        ),
    ]
