# Generated by Django 3.0.5 on 2020-05-21 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200506_0447'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(default='unknown', max_length=1000, null=True),
        ),
    ]
